services:
  meeting-service:
    build: ./backend/meeting_service
    ports:
      - "5001:5001"
    networks:
      - backend-net
      - db-net
    environment:
      MYSQL_HOST: meeting-db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  calendar-service:
    build: ./backend/calendar_service
    ports:
      - "5002:5002"
    networks:
      - backend-net
      - db-net
    environment:
      MYSQL_HOST: calendar-db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  participant-service:
    build: ./backend/participant_service
    ports:
      - "5003:5003"
    networks:
      - backend-net
      - db-net
    environment:
      MYSQL_HOST: participant-db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  attachment-service:
    build: ./backend/attachment_service
    ports:
      - "5004:5004"
    networks:
      - backend-net
      - db-net
    environment:
      MYSQL_HOST: attachment-db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  linkage-service:
    build: ./backend/linkage_service
    ports:
      - "5005:5005"
    networks:
      - backend-net
      - db-net
    environment:
      MYSQL_HOST: linkage-db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  meeting-db:
    image: mysql:latest
    environment:
      MYSQL_HOST: meeting-db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/meeting-seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - db-net

  calendar-db:
    image: mysql:latest
    environment:
      MYSQL_HOST: calendar-db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/calendar-seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - db-net

  participant-db:
    image: mysql:latest
    environment:
      MYSQL_HOST: participant-db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/participant-seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - db-net

  attachment-db:
    image: mysql:latest
    environment:
      MYSQL_HOST: attachment-db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/attachment-seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - db-net
  
  linkage-db:
    image: mysql:latest
    environment:
      MYSQL_HOST: linkage-db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/linkage-seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - db-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - frontend-net
      - backend-net
    environment:
      NODE_ENV: development


networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge
  db-net:
    driver: bridge