services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - db
    # volumes:
      # - ./certs:/app/certs # SSL certificates
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend-net
      - db-net

  db:
    image: mysql:latest
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql # Seed data
      # - ./certs:/etc/mysql/certs # SSL certificates for MySQL
    # command: --ssl-ca=/etc/mysql/certs/ca-cert.pem --ssl-cert=/etc/mysql/certs/server-cert.pem --ssl-key=/etc/mysql/certs/server-key.pem
    networks:
      - db-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - frontend-net
      - backend-net
    environment:
      NODE_ENV: development

  cli_frontend:
    build: ./cli_frontend
    depends_on:
      - backend
    networks:
      - cli-frontend-net
      - backend-net
    tty: true

networks:
  cli-frontend-net:
    driver: bridge
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge
  db-net:
    driver: bridge
