services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - db
    # volumes:
      # - ./certs:/app/certs # SSL certificates
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - internal

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql # Seed data
      # - ./certs:/etc/mysql/certs # SSL certificates for MySQL
    # command: --ssl-ca=/etc/mysql/certs/ca-cert.pem --ssl-cert=/etc/mysql/certs/server-cert.pem --ssl-key=/etc/mysql/certs/server-key.pem
    networks:
      - internal

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - internal
  #     - external

networks:
  internal:
    driver: bridge
  external:
    driver: bridge
