services:
  attachment-service:
    build: ./backend/attachment_service
    ports:
      - "5001:5001"
    depends_on:
      - attachment-db
      - message_broker
    networks:
      - backend-net
      - db-net
    environment:
      MYSQL_HOST: ${ATTACHMENT_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  calendar-service:
    build: ./backend/calendar_service
    ports:
      - "5002:5002"
    depends_on:
      - calendar-db
      - message_broker
    networks:
      - backend-net
      - db-net
    environment:
      MYSQL_HOST: ${CALENDAR_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  linkage-service:
    build: ./backend/linkage_service
    ports:
      - "5003:5003"
    depends_on:
      - linkage-db
      - message_broker
    networks:
      - backend-net
      - db-net
    environment:
      MYSQL_HOST: ${LINKAGE_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  meeting-service:
    build: ./backend/meeting_service
    ports:
      - "5004:5004"
    depends_on:
      - meeting-db
      - message_broker
    networks:
      - backend-net
      - db-net
    environment:
      MYSQL_HOST: ${MEETING_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  participant-service:
    build: ./backend/participant_service
    ports:
      - "5005:5005"
    depends_on:
      - participant-db
      - message_broker
    networks:
      - backend-net
      - db-net
    environment:
      MYSQL_HOST: ${PARTICIPANT_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  attachment-db:
    image: mysql:latest
    environment:
      MYSQL_HOST: ${ATTACHMENT_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/attachment-seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - db-net

  calendar-db:
    image: mysql:latest
    environment:
      MYSQL_HOST: ${CALENDAR_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/calendar-seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - db-net

  linkage-db:
    image: mysql:latest
    environment:
      MYSQL_HOST: ${LINKAGE_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/linkage-seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - db-net

  meeting-db:
    image: mysql:latest
    environment:
      MYSQL_HOST: ${MEETING_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/meeting-seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - db-net

  participant-db:
    image: mysql:latest
    environment:
      MYSQL_HOST: ${PARTICIPANT_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/participant-seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - db-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - frontend-net
      - backend-net
    environment:
      NODE_ENV: development

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Link to your NGINX config
    depends_on:
      - attachment-service
      - calendar-service
      - meeting-service
      - participant-service
    networks:
      - frontend-net
      - backend-net

  cli_frontend:
    build: ./cli_frontend
    depends_on:
      - attachment-service
      - calendar-service
      - meeting-service
      - participant-service
    networks:
      - cli-frontend-net
      - backend-net
    tty: true

  message_broker:
    build: ./message_broker
    ports:
      - "5672:5672" # Default AMQP RabbitMQ port
      - "15672:15672" # Management UI port
    networks:
      - backend-net
      - db-net

  meetings_consumer:
    build: ./event_consumers/meetings_consumer
    depends_on:
      - message_broker
    networks:
      - backend-net

  attachments_consumer:
    build: ./event_consumers/attachments_consumer
    depends_on:
      - message_broker
    networks:
      - backend-net

  participants_consumer:
    build: ./event_consumers/participants_consumer
    depends_on:
      - message_broker
    networks:
      - backend-net

networks:
  cli-frontend-net:
    driver: bridge
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge
  db-net:
    driver: bridge