services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - db
      - rabbitmq
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend-net
      - db-net

  db:
    image: mysql:latest
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - db-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - frontend-net
      - backend-net
    environment:
      NODE_ENV: development

  cli_frontend:
    build: ./cli_frontend
    depends_on:
      - backend
    networks:
      - cli-frontend-net
      - backend-net
    tty: true

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP port for message broker
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser # TODO: Replace with password using environment variables
      RABBITMQ_DEFAULT_PASS: rabbitpassword # TODO: Replace with password using environment variables
    networks:
      - backend-net

networks:
  cli-frontend-net:
    driver: bridge
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge
  db-net:
    driver: bridge
