version: '3'
services:
  meeting-service:
    build: ./meeting-service
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: meeting_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password

  calendar-service:
    build: ./calendar-service
    ports:
      - "5001:5001"
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: calendar_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password

  participant-service:
    build: ./participant-service
    ports:
      - "5002:5002"
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: participant_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password

  attachment-service:
    build: ./attachment-service
    ports:
      - "5003:5003"
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: attachment_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
