version: '3'
services:
  meeting-service:
    build: ./meeting-service
    ports:
      - "5000:5000"
    networks:
      - backend-net
      - db-net
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: meeting_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password

  calendar-service:
    build: ./calendar-service
    ports:
      - "5001:5001"
    networks:
      - backend-net
      - db-net
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: calendar_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password

  participant-service:
    build: ./participant-service
    ports:
      - "5002:5002"
    networks:
      - backend-net
      - db-net
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: participant_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password

  attachment-service:
    build: ./attachment-service
    ports:
      - "5003:5003"
    networks:
      - backend-net
      - db-net
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: attachment_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - frontend-net
      - backend-net
    environment:
      NODE_ENV: development


networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge
  db-net:
    driver: bridge