# Use a Python base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install dependencies for the participant service
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port the participant service will run on
EXPOSE 5005

# Define the command to run the participant service
CMD ["python", "src/app.py"]
